namespace NJRAT
{
	// Token: 0x0200000A RID: 10
	
	public partial class DDoS : global::System.Windows.Forms.Form
	{
		// Token: 0x0600005C RID: 92 RVA: 0x00149BA8 File Offset: 0x00147FA8
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x0600005D RID: 93 RVA: 0x00149BF8 File Offset: 0x00147FF8
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::NJRAT.DDoS));
			this.Button1 = new global::System.Windows.Forms.Button();
			this.TextBox1 = new global::System.Windows.Forms.TextBox();
			this.TextBox2 = new global::System.Windows.Forms.TextBox();
			this.ComboBox1 = new global::System.Windows.Forms.ComboBox();
			this.TrackBar1 = new global::System.Windows.Forms.TrackBar();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.GroupBox2 = new global::System.Windows.Forms.GroupBox();
			this.Button2 = new global::System.Windows.Forms.Button();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.TextBox3 = new global::System.Windows.Forms.TextBox();
			this.Button3 = new global::System.Windows.Forms.Button();
			this.GroupBox3 = new global::System.Windows.Forms.GroupBox();
			this.ColumnHeader1 = new global::System.Windows.Forms.ColumnHeader();
			this.Timer1 = new global::System.Windows.Forms.Timer(this.components);
			this.TextBox5 = new global::System.Windows.Forms.TextBox();
			this.Panel1 = new global::System.Windows.Forms.Panel();
			this.GroupBox4 = new global::System.Windows.Forms.GroupBox();
			this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
			this.GroupBox5 = new global::System.Windows.Forms.GroupBox();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.TextBox4 = new global::System.Windows.Forms.TextBox();
			this.PictureBox1 = new global::System.Windows.Forms.PictureBox();
			this.Label5 = new global::System.Windows.Forms.Label();
			((global::System.ComponentModel.ISupportInitialize)this.TrackBar1).BeginInit();
			this.GroupBox2.SuspendLayout();
			this.GroupBox3.SuspendLayout();
			this.Panel1.SuspendLayout();
			this.GroupBox4.SuspendLayout();
			this.GroupBox1.SuspendLayout();
			this.GroupBox5.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).BeginInit();
			this.SuspendLayout();
			this.Button1.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			global::System.Windows.Forms.Control button = this.Button1;
			global::System.Drawing.Point point = new global::System.Drawing.Point(6, 16);
			button.Location = point;
			this.Button1.Name = "Button1";
			global::System.Windows.Forms.Control button2 = this.Button1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(85, 86);
			button2.Size = size;
			this.Button1.TabIndex = 0;
			this.Button1.Text = "Start";
			this.Button1.UseVisualStyleBackColor = true;
			this.TextBox1.BackColor = global::System.Drawing.Color.Black;
			this.TextBox1.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TextBox1.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control textBox = this.TextBox1;
			point = new global::System.Drawing.Point(9, 33);
			textBox.Location = point;
			this.TextBox1.Name = "TextBox1";
			global::System.Windows.Forms.Control textBox2 = this.TextBox1;
			size = new global::System.Drawing.Size(275, 20);
			textBox2.Size = size;
			this.TextBox1.TabIndex = 1;
			this.TextBox1.Text = "127.0.0.1";
			this.TextBox2.BackColor = global::System.Drawing.Color.Black;
			this.TextBox2.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TextBox2.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control textBox3 = this.TextBox2;
			point = new global::System.Drawing.Point(9, 34);
			textBox3.Location = point;
			this.TextBox2.Name = "TextBox2";
			global::System.Windows.Forms.Control textBox4 = this.TextBox2;
			size = new global::System.Drawing.Size(74, 20);
			textBox4.Size = size;
			this.TextBox2.TabIndex = 2;
			this.TextBox2.Text = "80";
			this.ComboBox1.BackColor = global::System.Drawing.Color.Black;
			this.ComboBox1.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.ComboBox1.ForeColor = global::System.Drawing.Color.LimeGreen;
			this.ComboBox1.FormattingEnabled = true;
			this.ComboBox1.Items.AddRange(new object[] { "TCP", "UDP", "HTTP", "PING" });
			global::System.Windows.Forms.Control comboBox = this.ComboBox1;
			point = new global::System.Drawing.Point(89, 34);
			comboBox.Location = point;
			this.ComboBox1.Name = "ComboBox1";
			global::System.Windows.Forms.Control comboBox2 = this.ComboBox1;
			size = new global::System.Drawing.Size(85, 22);
			comboBox2.Size = size;
			this.ComboBox1.TabIndex = 5;
			this.ComboBox1.Text = "UDP";
			global::System.Windows.Forms.Control trackBar = this.TrackBar1;
			point = new global::System.Drawing.Point(9, 33);
			trackBar.Location = point;
			this.TrackBar1.Name = "TrackBar1";
			global::System.Windows.Forms.Control trackBar2 = this.TrackBar1;
			size = new global::System.Drawing.Size(632, 45);
			trackBar2.Size = size;
			this.TrackBar1.TabIndex = 6;
			this.Label1.AutoSize = true;
			global::System.Windows.Forms.Control label = this.Label1;
			point = new global::System.Drawing.Point(6, 16);
			label.Location = point;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control label2 = this.Label1;
			size = new global::System.Drawing.Size(61, 14);
			label2.Size = size;
			this.Label1.TabIndex = 7;
			this.Label1.Text = "IP Adress";
			this.Label2.AutoSize = true;
			global::System.Windows.Forms.Control label3 = this.Label2;
			point = new global::System.Drawing.Point(6, 15);
			label3.Location = point;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control label4 = this.Label2;
			size = new global::System.Drawing.Size(30, 14);
			label4.Size = size;
			this.Label2.TabIndex = 8;
			this.Label2.Text = "Port";
			this.Label3.AutoSize = true;
			global::System.Windows.Forms.Control label5 = this.Label3;
			point = new global::System.Drawing.Point(86, 15);
			label5.Location = point;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control label6 = this.Label3;
			size = new global::System.Drawing.Size(33, 14);
			label6.Size = size;
			this.Label3.TabIndex = 9;
			this.Label3.Text = "Type";
			this.Label4.AutoSize = true;
			global::System.Windows.Forms.Control label7 = this.Label4;
			point = new global::System.Drawing.Point(224, 16);
			label7.Location = point;
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control label8 = this.Label4;
			size = new global::System.Drawing.Size(209, 14);
			label8.Size = size;
			this.Label4.TabIndex = 10;
			this.Label4.Text = "Hight <---------------------------------> Low";
			this.GroupBox2.Controls.Add(this.Button2);
			this.GroupBox2.Controls.Add(this.Label6);
			this.GroupBox2.Controls.Add(this.TextBox3);
			this.GroupBox2.Controls.Add(this.Button3);
			this.GroupBox2.Controls.Add(this.Label1);
			this.GroupBox2.Controls.Add(this.TextBox1);
			this.GroupBox2.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control groupBox = this.GroupBox2;
			point = new global::System.Drawing.Point(167, 12);
			groupBox.Location = point;
			this.GroupBox2.Name = "GroupBox2";
			global::System.Windows.Forms.Control groupBox2 = this.GroupBox2;
			size = new global::System.Drawing.Size(364, 108);
			groupBox2.Size = size;
			this.GroupBox2.TabIndex = 12;
			this.GroupBox2.TabStop = false;
			this.GroupBox2.Text = "Victim";
			this.Button2.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			global::System.Windows.Forms.Control button3 = this.Button2;
			point = new global::System.Drawing.Point(290, 73);
			button3.Location = point;
			this.Button2.Name = "Button2";
			global::System.Windows.Forms.Control button4 = this.Button2;
			size = new global::System.Drawing.Size(63, 22);
			button4.Size = size;
			this.Button2.TabIndex = 13;
			this.Button2.Text = "Lock On";
			this.Button2.UseVisualStyleBackColor = true;
			this.Label6.AutoSize = true;
			global::System.Windows.Forms.Control label9 = this.Label6;
			point = new global::System.Drawing.Point(6, 56);
			label9.Location = point;
			this.Label6.Name = "Label6";
			global::System.Windows.Forms.Control label10 = this.Label6;
			size = new global::System.Drawing.Size(28, 14);
			label10.Size = size;
			this.Label6.TabIndex = 12;
			this.Label6.Text = "URL";
			this.TextBox3.BackColor = global::System.Drawing.Color.Black;
			this.TextBox3.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TextBox3.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control textBox5 = this.TextBox3;
			point = new global::System.Drawing.Point(9, 73);
			textBox5.Location = point;
			this.TextBox3.Name = "TextBox3";
			global::System.Windows.Forms.Control textBox6 = this.TextBox3;
			size = new global::System.Drawing.Size(275, 20);
			textBox6.Size = size;
			this.TextBox3.TabIndex = 11;
			this.TextBox3.Text = "www.exsample.com";
			this.Button3.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			global::System.Windows.Forms.Control button5 = this.Button3;
			point = new global::System.Drawing.Point(290, 33);
			button5.Location = point;
			this.Button3.Name = "Button3";
			global::System.Windows.Forms.Control button6 = this.Button3;
			size = new global::System.Drawing.Size(63, 22);
			button6.Size = size;
			this.Button3.TabIndex = 10;
			this.Button3.Text = "Lock On";
			this.Button3.UseVisualStyleBackColor = true;
			this.GroupBox3.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control groupBox3 = this.GroupBox3;
			point = new global::System.Drawing.Point(167, 195);
			groupBox3.Location = point;
			this.GroupBox3.Name = "GroupBox3";
			global::System.Windows.Forms.Control groupBox4 = this.GroupBox3;
			size = new global::System.Drawing.Size(655, 115);
			groupBox4.Size = size;
			this.GroupBox3.TabIndex = 13;
			this.GroupBox3.TabStop = false;
			this.GroupBox3.Text = "Logs";
			this.ColumnHeader1.Width = 540;
			this.Timer1.Enabled = true;
			this.TextBox5.BackColor = global::System.Drawing.Color.Black;
			this.TextBox5.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TextBox5.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.TextBox5.Enabled = false;
			this.TextBox5.Font = new global::System.Drawing.Font("Arial", 38f, global::System.Drawing.FontStyle.Bold | global::System.Drawing.FontStyle.Italic, global::System.Drawing.GraphicsUnit.Point, 0);
			this.TextBox5.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control textBox7 = this.TextBox5;
			point = new global::System.Drawing.Point(0, 0);
			textBox7.Location = point;
			this.TextBox5.Multiline = true;
			this.TextBox5.Name = "TextBox5";
			global::System.Windows.Forms.Control textBox8 = this.TextBox5;
			size = new global::System.Drawing.Size(653, 61);
			textBox8.Size = size;
			this.TextBox5.TabIndex = 0;
			this.TextBox5.Text = "NONE!";
			this.TextBox5.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.Panel1.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.Panel1.Controls.Add(this.TextBox5);
			global::System.Windows.Forms.Control panel = this.Panel1;
			point = new global::System.Drawing.Point(167, 126);
			panel.Location = point;
			this.Panel1.Name = "Panel1";
			global::System.Windows.Forms.Control panel2 = this.Panel1;
			size = new global::System.Drawing.Size(655, 63);
			panel2.Size = size;
			this.Panel1.TabIndex = 15;
			this.GroupBox4.Controls.Add(this.Button1);
			this.GroupBox4.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control groupBox5 = this.GroupBox4;
			point = new global::System.Drawing.Point(723, 13);
			groupBox5.Location = point;
			this.GroupBox4.Name = "GroupBox4";
			global::System.Windows.Forms.Control groupBox6 = this.GroupBox4;
			size = new global::System.Drawing.Size(99, 108);
			groupBox6.Size = size;
			this.GroupBox4.TabIndex = 16;
			this.GroupBox4.TabStop = false;
			this.GroupBox4.Text = "On/Off";
			this.GroupBox1.Controls.Add(this.TrackBar1);
			this.GroupBox1.Controls.Add(this.Label4);
			this.GroupBox1.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control groupBox7 = this.GroupBox1;
			point = new global::System.Drawing.Point(167, 316);
			groupBox7.Location = point;
			this.GroupBox1.Name = "GroupBox1";
			global::System.Windows.Forms.Control groupBox8 = this.GroupBox1;
			size = new global::System.Drawing.Size(655, 80);
			groupBox8.Size = size;
			this.GroupBox1.TabIndex = 17;
			this.GroupBox1.TabStop = false;
			this.GroupBox1.Text = "Packets";
			this.GroupBox5.Controls.Add(this.Label7);
			this.GroupBox5.Controls.Add(this.TextBox4);
			this.GroupBox5.Controls.Add(this.Label2);
			this.GroupBox5.Controls.Add(this.TextBox2);
			this.GroupBox5.Controls.Add(this.Label3);
			this.GroupBox5.Controls.Add(this.ComboBox1);
			this.GroupBox5.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control groupBox9 = this.GroupBox5;
			point = new global::System.Drawing.Point(537, 13);
			groupBox9.Location = point;
			this.GroupBox5.Name = "GroupBox5";
			global::System.Windows.Forms.Control groupBox10 = this.GroupBox5;
			size = new global::System.Drawing.Size(180, 108);
			groupBox10.Size = size;
			this.GroupBox5.TabIndex = 17;
			this.GroupBox5.TabStop = false;
			this.Label7.AutoSize = true;
			global::System.Windows.Forms.Control label11 = this.Label7;
			point = new global::System.Drawing.Point(6, 63);
			label11.Location = point;
			this.Label7.Name = "Label7";
			global::System.Windows.Forms.Control label12 = this.Label7;
			size = new global::System.Drawing.Size(131, 14);
			label12.Size = size;
			this.Label7.TabIndex = 11;
			this.Label7.Text = "PING Flood Packet Size";
			this.TextBox4.BackColor = global::System.Drawing.Color.Black;
			this.TextBox4.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TextBox4.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control textBox9 = this.TextBox4;
			point = new global::System.Drawing.Point(9, 82);
			textBox9.Location = point;
			this.TextBox4.Name = "TextBox4";
			global::System.Windows.Forms.Control textBox10 = this.TextBox4;
			size = new global::System.Drawing.Size(165, 20);
			textBox10.Size = size;
			this.TextBox4.TabIndex = 10;
			this.TextBox4.Text = "36000";
			this.PictureBox1.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox1.Image");
			global::System.Windows.Forms.Control pictureBox = this.PictureBox1;
			point = new global::System.Drawing.Point(-1, -9);
			pictureBox.Location = point;
			this.PictureBox1.Name = "PictureBox1";
			global::System.Windows.Forms.Control pictureBox2 = this.PictureBox1;
			size = new global::System.Drawing.Size(162, 388);
			pictureBox2.Size = size;
			this.PictureBox1.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
			this.PictureBox1.TabIndex = 18;
			this.PictureBox1.TabStop = false;
			this.Label5.AutoSize = true;
			this.Label5.Font = new global::System.Drawing.Font("Arial", 8f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label5.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control label13 = this.Label5;
			point = new global::System.Drawing.Point(12, 382);
			label13.Location = point;
			this.Label5.Name = "Label5";
			global::System.Windows.Forms.Control label14 = this.Label5;
			size = new global::System.Drawing.Size(13, 14);
			label14.Size = size;
			this.Label5.TabIndex = 19;
			this.Label5.Text = "..";
			global::System.Drawing.SizeF sizeF = new global::System.Drawing.SizeF(7f, 14f);
			this.AutoScaleDimensions = sizeF;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = global::System.Drawing.Color.Black;
			size = new global::System.Drawing.Size(834, 404);
			this.ClientSize = size;
			this.Controls.Add(this.Label5);
			this.Controls.Add(this.PictureBox1);
			this.Controls.Add(this.GroupBox5);
			this.Controls.Add(this.GroupBox1);
			this.Controls.Add(this.GroupBox4);
			this.Controls.Add(this.Panel1);
			this.Controls.Add(this.GroupBox2);
			this.Controls.Add(this.GroupBox3);
			this.Font = new global::System.Drawing.Font("Arial", 8f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.ForeColor = global::System.Drawing.Color.LimeGreen;
			this.Name = "DDoS";
			((global::System.ComponentModel.ISupportInitialize)this.TrackBar1).EndInit();
			this.GroupBox2.ResumeLayout(false);
			this.GroupBox2.PerformLayout();
			this.GroupBox3.ResumeLayout(false);
			this.Panel1.ResumeLayout(false);
			this.Panel1.PerformLayout();
			this.GroupBox4.ResumeLayout(false);
			this.GroupBox1.ResumeLayout(false);
			this.GroupBox1.PerformLayout();
			this.GroupBox5.ResumeLayout(false);
			this.GroupBox5.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).EndInit();
			this.ResumeLayout(false);
			this.PerformLayout();
		}

		// Token: 0x04000029 RID: 41
		private global::System.ComponentModel.IContainer components;
	}
}
