namespace NJRAT
{
	// Token: 0x02000013 RID: 19
	
	public partial class fun : global::System.Windows.Forms.Form
	{
		// Token: 0x06000202 RID: 514 RVA: 0x00159B48 File Offset: 0x00157F48
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06000203 RID: 515 RVA: 0x00159B98 File Offset: 0x00157F98
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::NJRAT.fun));
			this.ImageList1 = new global::System.Windows.Forms.ImageList(this.components);
			this.GroupBox7 = new global::System.Windows.Forms.GroupBox();
			this.Button14 = new global::System.Windows.Forms.Button();
			this.Button15 = new global::System.Windows.Forms.Button();
			this.GroupBox2 = new global::System.Windows.Forms.GroupBox();
			this.Button3 = new global::System.Windows.Forms.Button();
			this.Button4 = new global::System.Windows.Forms.Button();
			this.GroupBox8 = new global::System.Windows.Forms.GroupBox();
			this.Button16 = new global::System.Windows.Forms.Button();
			this.Button17 = new global::System.Windows.Forms.Button();
			this.GroupBox6 = new global::System.Windows.Forms.GroupBox();
			this.Button22 = new global::System.Windows.Forms.Button();
			this.Button23 = new global::System.Windows.Forms.Button();
			this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
			this.Button1 = new global::System.Windows.Forms.Button();
			this.Button2 = new global::System.Windows.Forms.Button();
			this.GroupBox10 = new global::System.Windows.Forms.GroupBox();
			this.Button19 = new global::System.Windows.Forms.Button();
			this.Button18 = new global::System.Windows.Forms.Button();
			this.GroupBox9 = new global::System.Windows.Forms.GroupBox();
			this.Button12 = new global::System.Windows.Forms.Button();
			this.Button13 = new global::System.Windows.Forms.Button();
			this.GroupBox11 = new global::System.Windows.Forms.GroupBox();
			this.Button21 = new global::System.Windows.Forms.Button();
			this.Button20 = new global::System.Windows.Forms.Button();
			this.GroupBox25 = new global::System.Windows.Forms.GroupBox();
			this.Button28 = new global::System.Windows.Forms.Button();
			this.Button29 = new global::System.Windows.Forms.Button();
			this.GroupBox19 = new global::System.Windows.Forms.GroupBox();
			this.Button37 = new global::System.Windows.Forms.Button();
			this.Button36 = new global::System.Windows.Forms.Button();
			this.TextBox4 = new global::System.Windows.Forms.TextBox();
			this.Button56 = new global::System.Windows.Forms.Button();
			this.GroupBox18 = new global::System.Windows.Forms.GroupBox();
			this.Button40 = new global::System.Windows.Forms.Button();
			this.Button41 = new global::System.Windows.Forms.Button();
			this.Button42 = new global::System.Windows.Forms.Button();
			this.Button43 = new global::System.Windows.Forms.Button();
			this.Button44 = new global::System.Windows.Forms.Button();
			this.Button45 = new global::System.Windows.Forms.Button();
			this.Button46 = new global::System.Windows.Forms.Button();
			this.Button47 = new global::System.Windows.Forms.Button();
			this.Button48 = new global::System.Windows.Forms.Button();
			this.Button49 = new global::System.Windows.Forms.Button();
			this.Button50 = new global::System.Windows.Forms.Button();
			this.Button51 = new global::System.Windows.Forms.Button();
			this.Button52 = new global::System.Windows.Forms.Button();
			this.Check_Sound = new global::System.Windows.Forms.CheckBox();
			this.GroupBox20 = new global::System.Windows.Forms.GroupBox();
			this.RadioButton10 = new global::System.Windows.Forms.RadioButton();
			this.RadioButton9 = new global::System.Windows.Forms.RadioButton();
			this.RadioButton8 = new global::System.Windows.Forms.RadioButton();
			this.RadioButton7 = new global::System.Windows.Forms.RadioButton();
			this.RadioButton6 = new global::System.Windows.Forms.RadioButton();
			this.RadioButton5 = new global::System.Windows.Forms.RadioButton();
			this.GroupBox22 = new global::System.Windows.Forms.GroupBox();
			this.RadioButton4 = new global::System.Windows.Forms.RadioButton();
			this.PictureBox4 = new global::System.Windows.Forms.PictureBox();
			this.RadioButton3 = new global::System.Windows.Forms.RadioButton();
			this.PictureBox3 = new global::System.Windows.Forms.PictureBox();
			this.RadioButton2 = new global::System.Windows.Forms.RadioButton();
			this.PictureBox2 = new global::System.Windows.Forms.PictureBox();
			this.RadioButton1 = new global::System.Windows.Forms.RadioButton();
			this.PictureBox1 = new global::System.Windows.Forms.PictureBox();
			this.GroupBox21 = new global::System.Windows.Forms.GroupBox();
			this.TextBox5 = new global::System.Windows.Forms.TextBox();
			this.TextBox6 = new global::System.Windows.Forms.TextBox();
			this.Button39 = new global::System.Windows.Forms.Button();
			this.Button38 = new global::System.Windows.Forms.Button();
			this.Panel1 = new global::System.Windows.Forms.Panel();
			this.Panel2 = new global::System.Windows.Forms.Panel();
			this.GroupBox16 = new global::System.Windows.Forms.GroupBox();
			this.Button34 = new global::System.Windows.Forms.Button();
			this.TextBox1 = new global::System.Windows.Forms.TextBox();
			this.GroupBox3 = new global::System.Windows.Forms.GroupBox();
			this.Button5 = new global::System.Windows.Forms.Button();
			this.Button6 = new global::System.Windows.Forms.Button();
			this.Button7 = new global::System.Windows.Forms.Button();
			this.Panel4 = new global::System.Windows.Forms.Panel();
			this.Button53 = new global::System.Windows.Forms.Button();
			this.Panel6 = new global::System.Windows.Forms.Panel();
			this.Button55 = new global::System.Windows.Forms.Button();
			this.Panel7 = new global::System.Windows.Forms.Panel();
			this.GroupBox7.SuspendLayout();
			this.GroupBox2.SuspendLayout();
			this.GroupBox8.SuspendLayout();
			this.GroupBox6.SuspendLayout();
			this.GroupBox1.SuspendLayout();
			this.GroupBox10.SuspendLayout();
			this.GroupBox9.SuspendLayout();
			this.GroupBox11.SuspendLayout();
			this.GroupBox25.SuspendLayout();
			this.GroupBox19.SuspendLayout();
			this.GroupBox18.SuspendLayout();
			this.GroupBox20.SuspendLayout();
			this.GroupBox22.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox4).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox3).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).BeginInit();
			this.GroupBox21.SuspendLayout();
			this.Panel1.SuspendLayout();
			this.Panel2.SuspendLayout();
			this.GroupBox16.SuspendLayout();
			this.GroupBox3.SuspendLayout();
			this.Panel4.SuspendLayout();
			this.Panel6.SuspendLayout();
			this.Panel7.SuspendLayout();
			this.SuspendLayout();
			this.ImageList1.ImageStream = (global::System.Windows.Forms.ImageListStreamer)componentResourceManager.GetObject("ImageList1.ImageStream");
			this.ImageList1.TransparentColor = global::System.Drawing.Color.Transparent;
			this.ImageList1.Images.SetKeyName(0, "fun.png");
			this.ImageList1.Images.SetKeyName(1, "fun_manager.png");
			this.ImageList1.Images.SetKeyName(2, "box_warning.png");
			this.ImageList1.Images.SetKeyName(3, "clipboard.png");
			this.ImageList1.Images.SetKeyName(4, "script_bat.png");
			this.GroupBox7.Controls.Add(this.Button14);
			this.GroupBox7.Controls.Add(this.Button15);
			this.GroupBox7.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control groupBox = this.GroupBox7;
			global::System.Drawing.Point point = new global::System.Drawing.Point(420, 216);
			groupBox.Location = point;
			this.GroupBox7.Name = "GroupBox7";
			global::System.Windows.Forms.Control groupBox2 = this.GroupBox7;
			global::System.Drawing.Size size = new global::System.Drawing.Size(203, 54);
			groupBox2.Size = size;
			this.GroupBox7.TabIndex = 12;
			this.GroupBox7.TabStop = false;
			this.GroupBox7.Text = "Monitor";
			this.Button14.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button14.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button14.Image");
			global::System.Windows.Forms.Control button = this.Button14;
			point = new global::System.Drawing.Point(110, 15);
			button.Location = point;
			this.Button14.Name = "Button14";
			global::System.Windows.Forms.Control button2 = this.Button14;
			size = new global::System.Drawing.Size(87, 32);
			button2.Size = size;
			this.Button14.TabIndex = 1;
			this.Button14.Text = "Turn on";
			this.Button14.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageBeforeText;
			this.Button14.UseVisualStyleBackColor = true;
			this.Button15.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button15.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button15.Image");
			global::System.Windows.Forms.Control button3 = this.Button15;
			point = new global::System.Drawing.Point(8, 15);
			button3.Location = point;
			this.Button15.Name = "Button15";
			global::System.Windows.Forms.Control button4 = this.Button15;
			size = new global::System.Drawing.Size(87, 32);
			button4.Size = size;
			this.Button15.TabIndex = 0;
			this.Button15.Text = "Turn off";
			this.Button15.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageBeforeText;
			this.Button15.UseVisualStyleBackColor = true;
			this.GroupBox2.Controls.Add(this.Button3);
			this.GroupBox2.Controls.Add(this.Button4);
			this.GroupBox2.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control groupBox3 = this.GroupBox2;
			point = new global::System.Drawing.Point(1, 270);
			groupBox3.Location = point;
			this.GroupBox2.Name = "GroupBox2";
			global::System.Windows.Forms.Control groupBox4 = this.GroupBox2;
			size = new global::System.Drawing.Size(203, 54);
			groupBox4.Size = size;
			this.GroupBox2.TabIndex = 8;
			this.GroupBox2.TabStop = false;
			this.GroupBox2.Text = "Mouse/Keyboard";
			this.Button3.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button3.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button3.Image");
			global::System.Windows.Forms.Control button5 = this.Button3;
			point = new global::System.Drawing.Point(8, 15);
			button5.Location = point;
			this.Button3.Name = "Button3";
			global::System.Windows.Forms.Control button6 = this.Button3;
			size = new global::System.Drawing.Size(87, 32);
			button6.Size = size;
			this.Button3.TabIndex = 4;
			this.Button3.Text = "Unblock";
			this.Button3.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageBeforeText;
			this.Button3.UseVisualStyleBackColor = true;
			this.Button4.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button4.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button4.Image");
			global::System.Windows.Forms.Control button7 = this.Button4;
			point = new global::System.Drawing.Point(108, 15);
			button7.Location = point;
			this.Button4.Name = "Button4";
			global::System.Windows.Forms.Control button8 = this.Button4;
			size = new global::System.Drawing.Size(87, 32);
			button8.Size = size;
			this.Button4.TabIndex = 5;
			this.Button4.Text = "Block";
			this.Button4.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageBeforeText;
			this.Button4.UseVisualStyleBackColor = true;
			this.GroupBox8.Controls.Add(this.Button16);
			this.GroupBox8.Controls.Add(this.Button17);
			this.GroupBox8.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control groupBox5 = this.GroupBox8;
			point = new global::System.Drawing.Point(420, 162);
			groupBox5.Location = point;
			this.GroupBox8.Name = "GroupBox8";
			global::System.Windows.Forms.Control groupBox6 = this.GroupBox8;
			size = new global::System.Drawing.Size(203, 54);
			groupBox6.Size = size;
			this.GroupBox8.TabIndex = 13;
			this.GroupBox8.TabStop = false;
			this.GroupBox8.Text = "Mouse";
			this.Button16.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button16.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button16.Image");
			global::System.Windows.Forms.Control button9 = this.Button16;
			point = new global::System.Drawing.Point(110, 15);
			button9.Location = point;
			this.Button16.Name = "Button16";
			global::System.Windows.Forms.Control button10 = this.Button16;
			size = new global::System.Drawing.Size(87, 32);
			button10.Size = size;
			this.Button16.TabIndex = 1;
			this.Button16.Text = "Normal";
			this.Button16.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageBeforeText;
			this.Button16.UseVisualStyleBackColor = true;
			this.Button17.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button17.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button17.Image");
			global::System.Windows.Forms.Control button11 = this.Button17;
			point = new global::System.Drawing.Point(7, 15);
			button11.Location = point;
			this.Button17.Name = "Button17";
			global::System.Windows.Forms.Control button12 = this.Button17;
			size = new global::System.Drawing.Size(87, 32);
			button12.Size = size;
			this.Button17.TabIndex = 0;
			this.Button17.Text = "Reverse";
			this.Button17.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageBeforeText;
			this.Button17.UseVisualStyleBackColor = true;
			this.GroupBox6.Controls.Add(this.Button22);
			this.GroupBox6.Controls.Add(this.Button23);
			this.GroupBox6.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control groupBox7 = this.GroupBox6;
			point = new global::System.Drawing.Point(211, 216);
			groupBox7.Location = point;
			this.GroupBox6.Name = "GroupBox6";
			global::System.Windows.Forms.Control groupBox8 = this.GroupBox6;
			size = new global::System.Drawing.Size(203, 54);
			groupBox8.Size = size;
			this.GroupBox6.TabIndex = 14;
			this.GroupBox6.TabStop = false;
			this.GroupBox6.Text = "Task Manager";
			this.Button22.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button22.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button22.Image");
			global::System.Windows.Forms.Control button13 = this.Button22;
			point = new global::System.Drawing.Point(110, 15);
			button13.Location = point;
			this.Button22.Name = "Button22";
			global::System.Windows.Forms.Control button14 = this.Button22;
			size = new global::System.Drawing.Size(87, 32);
			button14.Size = size;
			this.Button22.TabIndex = 10;
			this.Button22.Text = "Disable";
			this.Button22.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageBeforeText;
			this.Button22.UseVisualStyleBackColor = true;
			this.Button23.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button23.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button23.Image");
			global::System.Windows.Forms.Control button15 = this.Button23;
			point = new global::System.Drawing.Point(8, 15);
			button15.Location = point;
			this.Button23.Name = "Button23";
			global::System.Windows.Forms.Control button16 = this.Button23;
			size = new global::System.Drawing.Size(87, 32);
			button16.Size = size;
			this.Button23.TabIndex = 9;
			this.Button23.Text = "Enable";
			this.Button23.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageBeforeText;
			this.Button23.UseVisualStyleBackColor = true;
			this.GroupBox1.Controls.Add(this.Button1);
			this.GroupBox1.Controls.Add(this.Button2);
			this.GroupBox1.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control groupBox9 = this.GroupBox1;
			point = new global::System.Drawing.Point(1, 162);
			groupBox9.Location = point;
			this.GroupBox1.Name = "GroupBox1";
			global::System.Windows.Forms.Control groupBox10 = this.GroupBox1;
			size = new global::System.Drawing.Size(203, 54);
			groupBox10.Size = size;
			this.GroupBox1.TabIndex = 9;
			this.GroupBox1.TabStop = false;
			this.GroupBox1.Text = "CD-ROM";
			this.Button1.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button1.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button1.Image");
			global::System.Windows.Forms.Control button17 = this.Button1;
			point = new global::System.Drawing.Point(8, 15);
			button17.Location = point;
			this.Button1.Name = "Button1";
			global::System.Windows.Forms.Control button18 = this.Button1;
			size = new global::System.Drawing.Size(87, 32);
			button18.Size = size;
			this.Button1.TabIndex = 2;
			this.Button1.Text = "Open";
			this.Button1.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageBeforeText;
			this.Button1.UseVisualStyleBackColor = true;
			this.Button2.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button2.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button2.Image");
			global::System.Windows.Forms.Control button19 = this.Button2;
			point = new global::System.Drawing.Point(110, 15);
			button19.Location = point;
			this.Button2.Name = "Button2";
			global::System.Windows.Forms.Control button20 = this.Button2;
			size = new global::System.Drawing.Size(87, 32);
			button20.Size = size;
			this.Button2.TabIndex = 3;
			this.Button2.Text = "Close";
			this.Button2.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageBeforeText;
			this.Button2.UseVisualStyleBackColor = true;
			this.GroupBox10.Controls.Add(this.Button19);
			this.GroupBox10.Controls.Add(this.Button18);
			this.GroupBox10.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control groupBox11 = this.GroupBox10;
			point = new global::System.Drawing.Point(421, 270);
			groupBox11.Location = point;
			this.GroupBox10.Name = "GroupBox10";
			global::System.Windows.Forms.Control groupBox12 = this.GroupBox10;
			size = new global::System.Drawing.Size(203, 54);
			groupBox12.Size = size;
			this.GroupBox10.TabIndex = 16;
			this.GroupBox10.TabStop = false;
			this.GroupBox10.Text = "Registry";
			this.Button19.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button19.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button19.Image");
			global::System.Windows.Forms.Control button21 = this.Button19;
			point = new global::System.Drawing.Point(8, 15);
			button21.Location = point;
			this.Button19.Name = "Button19";
			global::System.Windows.Forms.Control button22 = this.Button19;
			size = new global::System.Drawing.Size(87, 32);
			button22.Size = size;
			this.Button19.TabIndex = 3;
			this.Button19.Text = "Enable";
			this.Button19.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageBeforeText;
			this.Button19.UseVisualStyleBackColor = true;
			this.Button18.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button18.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button18.Image");
			global::System.Windows.Forms.Control button23 = this.Button18;
			point = new global::System.Drawing.Point(110, 15);
			button23.Location = point;
			this.Button18.Name = "Button18";
			global::System.Windows.Forms.Control button24 = this.Button18;
			size = new global::System.Drawing.Size(87, 32);
			button24.Size = size;
			this.Button18.TabIndex = 4;
			this.Button18.Text = "Disable";
			this.Button18.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageBeforeText;
			this.Button18.UseVisualStyleBackColor = true;
			this.GroupBox9.Controls.Add(this.Button12);
			this.GroupBox9.Controls.Add(this.Button13);
			this.GroupBox9.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control groupBox13 = this.GroupBox9;
			point = new global::System.Drawing.Point(1, 216);
			groupBox13.Location = point;
			this.GroupBox9.Name = "GroupBox9";
			global::System.Windows.Forms.Control groupBox14 = this.GroupBox9;
			size = new global::System.Drawing.Size(203, 54);
			groupBox14.Size = size;
			this.GroupBox9.TabIndex = 16;
			this.GroupBox9.TabStop = false;
			this.GroupBox9.Text = "CMD";
			this.Button12.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button12.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button12.Image");
			global::System.Windows.Forms.Control button25 = this.Button12;
			point = new global::System.Drawing.Point(8, 15);
			button25.Location = point;
			this.Button12.Name = "Button12";
			global::System.Windows.Forms.Control button26 = this.Button12;
			size = new global::System.Drawing.Size(87, 32);
			button26.Size = size;
			this.Button12.TabIndex = 0;
			this.Button12.Text = "Enable";
			this.Button12.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageBeforeText;
			this.Button12.UseVisualStyleBackColor = true;
			this.Button13.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button13.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button13.Image");
			global::System.Windows.Forms.Control button27 = this.Button13;
			point = new global::System.Drawing.Point(108, 15);
			button27.Location = point;
			this.Button13.Name = "Button13";
			global::System.Windows.Forms.Control button28 = this.Button13;
			size = new global::System.Drawing.Size(87, 32);
			button28.Size = size;
			this.Button13.TabIndex = 1;
			this.Button13.Text = "Disable";
			this.Button13.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageBeforeText;
			this.Button13.UseVisualStyleBackColor = true;
			this.GroupBox11.Controls.Add(this.Button21);
			this.GroupBox11.Controls.Add(this.Button20);
			this.GroupBox11.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control groupBox15 = this.GroupBox11;
			point = new global::System.Drawing.Point(211, 270);
			groupBox15.Location = point;
			this.GroupBox11.Name = "GroupBox11";
			global::System.Windows.Forms.Control groupBox16 = this.GroupBox11;
			size = new global::System.Drawing.Size(203, 54);
			groupBox16.Size = size;
			this.GroupBox11.TabIndex = 16;
			this.GroupBox11.TabStop = false;
			this.GroupBox11.Text = "System Restore";
			this.Button21.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button21.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button21.Image");
			global::System.Windows.Forms.Control button29 = this.Button21;
			point = new global::System.Drawing.Point(8, 15);
			button29.Location = point;
			this.Button21.Name = "Button21";
			global::System.Windows.Forms.Control button30 = this.Button21;
			size = new global::System.Drawing.Size(87, 32);
			button30.Size = size;
			this.Button21.TabIndex = 6;
			this.Button21.Text = "Enable";
			this.Button21.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageBeforeText;
			this.Button21.UseVisualStyleBackColor = true;
			this.Button20.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button20.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button20.Image");
			global::System.Windows.Forms.Control button31 = this.Button20;
			point = new global::System.Drawing.Point(110, 15);
			button31.Location = point;
			this.Button20.Name = "Button20";
			global::System.Windows.Forms.Control button32 = this.Button20;
			size = new global::System.Drawing.Size(87, 32);
			button32.Size = size;
			this.Button20.TabIndex = 7;
			this.Button20.Text = "Disable";
			this.Button20.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageBeforeText;
			this.Button20.UseVisualStyleBackColor = true;
			this.GroupBox25.Controls.Add(this.Button28);
			this.GroupBox25.Controls.Add(this.Button29);
			this.GroupBox25.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control groupBox17 = this.GroupBox25;
			point = new global::System.Drawing.Point(211, 162);
			groupBox17.Location = point;
			this.GroupBox25.Name = "GroupBox25";
			global::System.Windows.Forms.Control groupBox18 = this.GroupBox25;
			size = new global::System.Drawing.Size(203, 54);
			groupBox18.Size = size;
			this.GroupBox25.TabIndex = 11;
			this.GroupBox25.TabStop = false;
			this.GroupBox25.Text = "Cursor";
			this.Button28.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button28.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button28.Image");
			global::System.Windows.Forms.Control button33 = this.Button28;
			point = new global::System.Drawing.Point(8, 15);
			button33.Location = point;
			this.Button28.Name = "Button28";
			global::System.Windows.Forms.Control button34 = this.Button28;
			size = new global::System.Drawing.Size(87, 32);
			button34.Size = size;
			this.Button28.TabIndex = 20;
			this.Button28.Text = "Hide";
			this.Button28.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageBeforeText;
			this.Button28.UseVisualStyleBackColor = true;
			this.Button29.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button29.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button29.Image");
			global::System.Windows.Forms.Control button35 = this.Button29;
			point = new global::System.Drawing.Point(108, 16);
			button35.Location = point;
			this.Button29.Name = "Button29";
			global::System.Windows.Forms.Control button36 = this.Button29;
			size = new global::System.Drawing.Size(87, 32);
			button36.Size = size;
			this.Button29.TabIndex = 21;
			this.Button29.Text = "Show";
			this.Button29.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageBeforeText;
			this.Button29.UseVisualStyleBackColor = true;
			this.GroupBox19.Controls.Add(this.Button37);
			this.GroupBox19.Controls.Add(this.Button36);
			this.GroupBox19.Controls.Add(this.TextBox4);
			this.GroupBox19.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control groupBox19 = this.GroupBox19;
			point = new global::System.Drawing.Point(352, 1);
			groupBox19.Location = point;
			this.GroupBox19.Name = "GroupBox19";
			global::System.Windows.Forms.Control groupBox20 = this.GroupBox19;
			size = new global::System.Drawing.Size(271, 66);
			groupBox20.Size = size;
			this.GroupBox19.TabIndex = 17;
			this.GroupBox19.TabStop = false;
			this.GroupBox19.Text = "Speak";
			this.Button37.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			global::System.Windows.Forms.Control button37 = this.Button37;
			point = new global::System.Drawing.Point(216, 35);
			button37.Location = point;
			this.Button37.Name = "Button37";
			global::System.Windows.Forms.Control button38 = this.Button37;
			size = new global::System.Drawing.Size(50, 25);
			button38.Size = size;
			this.Button37.TabIndex = 1;
			this.Button37.Text = "Test";
			this.Button37.UseVisualStyleBackColor = true;
			this.Button36.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			global::System.Windows.Forms.Control button39 = this.Button36;
			point = new global::System.Drawing.Point(216, 15);
			button39.Location = point;
			this.Button36.Name = "Button36";
			global::System.Windows.Forms.Control button40 = this.Button36;
			size = new global::System.Drawing.Size(50, 26);
			button40.Size = size;
			this.Button36.TabIndex = 1;
			this.Button36.Text = "Send";
			this.Button36.UseVisualStyleBackColor = true;
			this.TextBox4.BackColor = global::System.Drawing.Color.Black;
			this.TextBox4.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TextBox4.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control textBox = this.TextBox4;
			point = new global::System.Drawing.Point(7, 15);
			textBox.Location = point;
			this.TextBox4.Multiline = true;
			this.TextBox4.Name = "TextBox4";
			global::System.Windows.Forms.Control textBox2 = this.TextBox4;
			size = new global::System.Drawing.Size(203, 43);
			textBox2.Size = size;
			this.TextBox4.TabIndex = 0;
			this.Button56.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button56.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button56.Image");
			global::System.Windows.Forms.Control button41 = this.Button56;
			point = new global::System.Drawing.Point(352, 131);
			button41.Location = point;
			this.Button56.Name = "Button56";
			global::System.Windows.Forms.Control button42 = this.Button56;
			size = new global::System.Drawing.Size(190, 25);
			button42.Size = size;
			this.Button56.TabIndex = 19;
			this.Button56.Text = "Play WAV Hidden";
			this.Button56.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageBeforeText;
			this.Button56.UseVisualStyleBackColor = true;
			this.GroupBox18.Controls.Add(this.Button40);
			this.GroupBox18.Controls.Add(this.Button41);
			this.GroupBox18.Controls.Add(this.Button42);
			this.GroupBox18.Controls.Add(this.Button43);
			this.GroupBox18.Controls.Add(this.Button44);
			this.GroupBox18.Controls.Add(this.Button45);
			this.GroupBox18.Controls.Add(this.Button46);
			this.GroupBox18.Controls.Add(this.Button47);
			this.GroupBox18.Controls.Add(this.Button48);
			this.GroupBox18.Controls.Add(this.Button49);
			this.GroupBox18.Controls.Add(this.Button50);
			this.GroupBox18.Controls.Add(this.Button51);
			this.GroupBox18.Controls.Add(this.Button52);
			this.GroupBox18.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control groupBox21 = this.GroupBox18;
			point = new global::System.Drawing.Point(84, 1);
			groupBox21.Location = point;
			this.GroupBox18.Name = "GroupBox18";
			global::System.Windows.Forms.Control groupBox22 = this.GroupBox18;
			size = new global::System.Drawing.Size(262, 155);
			groupBox22.Size = size;
			this.GroupBox18.TabIndex = 21;
			this.GroupBox18.TabStop = false;
			this.GroupBox18.Text = "Piano";
			this.Button40.BackColor = global::System.Drawing.Color.Black;
			this.Button40.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button40.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control button43 = this.Button40;
			point = new global::System.Drawing.Point(184, 15);
			button43.Location = point;
			this.Button40.Name = "Button40";
			global::System.Windows.Forms.Control button44 = this.Button40;
			size = new global::System.Drawing.Size(20, 91);
			button44.Size = size;
			this.Button40.TabIndex = 26;
			this.Button40.UseVisualStyleBackColor = false;
			this.Button41.BackColor = global::System.Drawing.Color.Black;
			this.Button41.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button41.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control button45 = this.Button41;
			point = new global::System.Drawing.Point(152, 15);
			button45.Location = point;
			this.Button41.Name = "Button41";
			global::System.Windows.Forms.Control button46 = this.Button41;
			size = new global::System.Drawing.Size(20, 91);
			button46.Size = size;
			this.Button41.TabIndex = 25;
			this.Button41.UseVisualStyleBackColor = false;
			this.Button42.BackColor = global::System.Drawing.Color.Black;
			this.Button42.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button42.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control button47 = this.Button42;
			point = new global::System.Drawing.Point(124, 15);
			button47.Location = point;
			this.Button42.Name = "Button42";
			global::System.Windows.Forms.Control button48 = this.Button42;
			size = new global::System.Drawing.Size(20, 91);
			button48.Size = size;
			this.Button42.TabIndex = 24;
			this.Button42.UseVisualStyleBackColor = false;
			this.Button43.BackColor = global::System.Drawing.Color.Black;
			this.Button43.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button43.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control button49 = this.Button43;
			point = new global::System.Drawing.Point(59, 15);
			button49.Location = point;
			this.Button43.Name = "Button43";
			global::System.Windows.Forms.Control button50 = this.Button43;
			size = new global::System.Drawing.Size(20, 91);
			button50.Size = size;
			this.Button43.TabIndex = 29;
			this.Button43.UseVisualStyleBackColor = false;
			this.Button44.BackColor = global::System.Drawing.Color.Black;
			this.Button44.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button44.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control button51 = this.Button44;
			point = new global::System.Drawing.Point(27, 15);
			button51.Location = point;
			this.Button44.Name = "Button44";
			global::System.Windows.Forms.Control button52 = this.Button44;
			size = new global::System.Drawing.Size(20, 91);
			button52.Size = size;
			this.Button44.TabIndex = 28;
			this.Button44.UseVisualStyleBackColor = false;
			this.Button45.BackColor = global::System.Drawing.Color.White;
			this.Button45.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button45.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control button53 = this.Button45;
			point = new global::System.Drawing.Point(225, 15);
			button53.Location = point;
			this.Button45.Name = "Button45";
			global::System.Windows.Forms.Control button54 = this.Button45;
			size = new global::System.Drawing.Size(30, 129);
			button54.Size = size;
			this.Button45.TabIndex = 27;
			this.Button45.UseVisualStyleBackColor = false;
			this.Button46.BackColor = global::System.Drawing.Color.White;
			this.Button46.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button46.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control button55 = this.Button46;
			point = new global::System.Drawing.Point(195, 15);
			button55.Location = point;
			this.Button46.Name = "Button46";
			global::System.Windows.Forms.Control button56 = this.Button46;
			size = new global::System.Drawing.Size(30, 129);
			button56.Size = size;
			this.Button46.TabIndex = 23;
			this.Button46.UseVisualStyleBackColor = false;
			this.Button47.BackColor = global::System.Drawing.Color.White;
			this.Button47.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button47.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control button57 = this.Button47;
			point = new global::System.Drawing.Point(164, 15);
			button57.Location = point;
			this.Button47.Name = "Button47";
			global::System.Windows.Forms.Control button58 = this.Button47;
			size = new global::System.Drawing.Size(30, 129);
			button58.Size = size;
			this.Button47.TabIndex = 19;
			this.Button47.UseVisualStyleBackColor = false;
			this.Button48.BackColor = global::System.Drawing.Color.White;
			this.Button48.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button48.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control button59 = this.Button48;
			point = new global::System.Drawing.Point(132, 15);
			button59.Location = point;
			this.Button48.Name = "Button48";
			global::System.Windows.Forms.Control button60 = this.Button48;
			size = new global::System.Drawing.Size(30, 129);
			button60.Size = size;
			this.Button48.TabIndex = 18;
			this.Button48.UseVisualStyleBackColor = false;
			this.Button49.BackColor = global::System.Drawing.Color.White;
			this.Button49.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button49.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control button61 = this.Button49;
			point = new global::System.Drawing.Point(100, 15);
			button61.Location = point;
			this.Button49.Name = "Button49";
			global::System.Windows.Forms.Control button62 = this.Button49;
			size = new global::System.Drawing.Size(30, 129);
			button62.Size = size;
			this.Button49.TabIndex = 17;
			this.Button49.UseVisualStyleBackColor = false;
			this.Button50.BackColor = global::System.Drawing.Color.White;
			this.Button50.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button50.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control button63 = this.Button50;
			point = new global::System.Drawing.Point(70, 15);
			button63.Location = point;
			this.Button50.Name = "Button50";
			global::System.Windows.Forms.Control button64 = this.Button50;
			size = new global::System.Drawing.Size(30, 129);
			button64.Size = size;
			this.Button50.TabIndex = 22;
			this.Button50.UseVisualStyleBackColor = false;
			this.Button51.BackColor = global::System.Drawing.Color.White;
			this.Button51.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button51.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control button65 = this.Button51;
			point = new global::System.Drawing.Point(37, 15);
			button65.Location = point;
			this.Button51.Name = "Button51";
			global::System.Windows.Forms.Control button66 = this.Button51;
			size = new global::System.Drawing.Size(30, 129);
			button66.Size = size;
			this.Button51.TabIndex = 21;
			this.Button51.UseVisualStyleBackColor = false;
			this.Button52.BackColor = global::System.Drawing.Color.White;
			this.Button52.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button52.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control button67 = this.Button52;
			point = new global::System.Drawing.Point(7, 15);
			button67.Location = point;
			this.Button52.Name = "Button52";
			global::System.Windows.Forms.Control button68 = this.Button52;
			size = new global::System.Drawing.Size(30, 129);
			button68.Size = size;
			this.Button52.TabIndex = 20;
			this.Button52.UseVisualStyleBackColor = false;
			this.Check_Sound.AutoSize = true;
			this.Check_Sound.Checked = true;
			this.Check_Sound.CheckState = global::System.Windows.Forms.CheckState.Checked;
			global::System.Windows.Forms.Control check_Sound = this.Check_Sound;
			point = new global::System.Drawing.Point(37, 373);
			check_Sound.Location = point;
			this.Check_Sound.Name = "Check_Sound";
			global::System.Windows.Forms.Control check_Sound2 = this.Check_Sound;
			size = new global::System.Drawing.Size(62, 18);
			check_Sound2.Size = size;
			this.Check_Sound.TabIndex = 16;
			this.Check_Sound.Text = "Enable";
			this.Check_Sound.UseVisualStyleBackColor = true;
			this.GroupBox20.Controls.Add(this.RadioButton10);
			this.GroupBox20.Controls.Add(this.RadioButton9);
			this.GroupBox20.Controls.Add(this.RadioButton8);
			this.GroupBox20.Controls.Add(this.RadioButton7);
			this.GroupBox20.Controls.Add(this.RadioButton6);
			this.GroupBox20.Controls.Add(this.RadioButton5);
			this.GroupBox20.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control groupBox23 = this.GroupBox20;
			point = new global::System.Drawing.Point(449, 1);
			groupBox23.Location = point;
			this.GroupBox20.Name = "GroupBox20";
			global::System.Windows.Forms.Control groupBox24 = this.GroupBox20;
			size = new global::System.Drawing.Size(177, 232);
			groupBox24.Size = size;
			this.GroupBox20.TabIndex = 27;
			this.GroupBox20.TabStop = false;
			this.GroupBox20.Text = "MessageBox Button";
			this.RadioButton10.AutoSize = true;
			global::System.Windows.Forms.Control radioButton = this.RadioButton10;
			point = new global::System.Drawing.Point(7, 146);
			radioButton.Location = point;
			this.RadioButton10.Name = "RadioButton10";
			global::System.Windows.Forms.Control radioButton2 = this.RadioButton10;
			size = new global::System.Drawing.Size(140, 18);
			radioButton2.Size = size;
			this.RadioButton10.TabIndex = 5;
			this.RadioButton10.Text = "Abort | Retry | Cancel";
			this.RadioButton10.UseVisualStyleBackColor = true;
			this.RadioButton9.AutoSize = true;
			global::System.Windows.Forms.Control radioButton3 = this.RadioButton9;
			point = new global::System.Drawing.Point(7, 122);
			radioButton3.Location = point;
			this.RadioButton9.Name = "RadioButton9";
			global::System.Windows.Forms.Control radioButton4 = this.RadioButton9;
			size = new global::System.Drawing.Size(100, 18);
			radioButton4.Size = size;
			this.RadioButton9.TabIndex = 4;
			this.RadioButton9.Text = "Retry | Cancel";
			this.RadioButton9.UseVisualStyleBackColor = true;
			this.RadioButton8.AutoSize = true;
			global::System.Windows.Forms.Control radioButton5 = this.RadioButton8;
			point = new global::System.Drawing.Point(7, 97);
			radioButton5.Location = point;
			this.RadioButton8.Name = "RadioButton8";
			global::System.Windows.Forms.Control radioButton6 = this.RadioButton8;
			size = new global::System.Drawing.Size(86, 18);
			radioButton6.Size = size;
			this.RadioButton8.TabIndex = 3;
			this.RadioButton8.Text = "OK | Cancel";
			this.RadioButton8.UseVisualStyleBackColor = true;
			this.RadioButton7.AutoSize = true;
			global::System.Windows.Forms.Control radioButton7 = this.RadioButton7;
			point = new global::System.Drawing.Point(7, 72);
			radioButton7.Location = point;
			this.RadioButton7.Name = "RadioButton7";
			global::System.Windows.Forms.Control radioButton8 = this.RadioButton7;
			size = new global::System.Drawing.Size(40, 18);
			radioButton8.Size = size;
			this.RadioButton7.TabIndex = 2;
			this.RadioButton7.Text = "OK";
			this.RadioButton7.UseVisualStyleBackColor = true;
			this.RadioButton6.AutoSize = true;
			global::System.Windows.Forms.Control radioButton9 = this.RadioButton6;
			point = new global::System.Drawing.Point(7, 47);
			radioButton9.Location = point;
			this.RadioButton6.Name = "RadioButton6";
			global::System.Windows.Forms.Control radioButton10 = this.RadioButton6;
			size = new global::System.Drawing.Size(114, 18);
			radioButton10.Size = size;
			this.RadioButton6.TabIndex = 1;
			this.RadioButton6.Text = "Yes | No | Cancel";
			this.RadioButton6.UseVisualStyleBackColor = true;
			this.RadioButton5.AutoSize = true;
			this.RadioButton5.Checked = true;
			global::System.Windows.Forms.Control radioButton11 = this.RadioButton5;
			point = new global::System.Drawing.Point(7, 23);
			radioButton11.Location = point;
			this.RadioButton5.Name = "RadioButton5";
			global::System.Windows.Forms.Control radioButton12 = this.RadioButton5;
			size = new global::System.Drawing.Size(68, 18);
			radioButton12.Size = size;
			this.RadioButton5.TabIndex = 0;
			this.RadioButton5.TabStop = true;
			this.RadioButton5.Text = "Yes | No";
			this.RadioButton5.UseVisualStyleBackColor = true;
			this.GroupBox22.Controls.Add(this.RadioButton4);
			this.GroupBox22.Controls.Add(this.PictureBox4);
			this.GroupBox22.Controls.Add(this.RadioButton3);
			this.GroupBox22.Controls.Add(this.PictureBox3);
			this.GroupBox22.Controls.Add(this.RadioButton2);
			this.GroupBox22.Controls.Add(this.PictureBox2);
			this.GroupBox22.Controls.Add(this.RadioButton1);
			this.GroupBox22.Controls.Add(this.PictureBox1);
			this.GroupBox22.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control groupBox25 = this.GroupBox22;
			point = new global::System.Drawing.Point(1, 1);
			groupBox25.Location = point;
			this.GroupBox22.Name = "GroupBox22";
			global::System.Windows.Forms.Control groupBox26 = this.GroupBox22;
			size = new global::System.Drawing.Size(439, 106);
			groupBox26.Size = size;
			this.GroupBox22.TabIndex = 25;
			this.GroupBox22.TabStop = false;
			this.GroupBox22.Text = "MessageBox Icon";
			this.RadioButton4.AutoSize = true;
			global::System.Windows.Forms.Control radioButton13 = this.RadioButton4;
			point = new global::System.Drawing.Point(369, 78);
			radioButton13.Location = point;
			this.RadioButton4.Name = "RadioButton4";
			global::System.Windows.Forms.Control radioButton14 = this.RadioButton4;
			size = new global::System.Drawing.Size(53, 18);
			radioButton14.Size = size;
			this.RadioButton4.TabIndex = 7;
			this.RadioButton4.TabStop = true;
			this.RadioButton4.Text = "Error";
			this.RadioButton4.UseVisualStyleBackColor = true;
			this.PictureBox4.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox4.Image");
			global::System.Windows.Forms.Control pictureBox = this.PictureBox4;
			point = new global::System.Drawing.Point(369, 23);
			pictureBox.Location = point;
			this.PictureBox4.Name = "PictureBox4";
			global::System.Windows.Forms.Control pictureBox2 = this.PictureBox4;
			size = new global::System.Drawing.Size(43, 42);
			pictureBox2.Size = size;
			this.PictureBox4.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
			this.PictureBox4.TabIndex = 6;
			this.PictureBox4.TabStop = false;
			this.RadioButton3.AutoSize = true;
			global::System.Windows.Forms.Control radioButton15 = this.RadioButton3;
			point = new global::System.Drawing.Point(247, 78);
			radioButton15.Location = point;
			this.RadioButton3.Name = "RadioButton3";
			global::System.Windows.Forms.Control radioButton16 = this.RadioButton3;
			size = new global::System.Drawing.Size(70, 18);
			radioButton16.Size = size;
			this.RadioButton3.TabIndex = 5;
			this.RadioButton3.TabStop = true;
			this.RadioButton3.Text = "Warning";
			this.RadioButton3.UseVisualStyleBackColor = true;
			this.PictureBox3.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox3.Image");
			global::System.Windows.Forms.Control pictureBox3 = this.PictureBox3;
			point = new global::System.Drawing.Point(261, 23);
			pictureBox3.Location = point;
			this.PictureBox3.Name = "PictureBox3";
			global::System.Windows.Forms.Control pictureBox4 = this.PictureBox3;
			size = new global::System.Drawing.Size(43, 42);
			pictureBox4.Size = size;
			this.PictureBox3.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
			this.PictureBox3.TabIndex = 4;
			this.PictureBox3.TabStop = false;
			this.RadioButton2.AutoSize = true;
			global::System.Windows.Forms.Control radioButton17 = this.RadioButton2;
			point = new global::System.Drawing.Point(133, 78);
			radioButton17.Location = point;
			this.RadioButton2.Name = "RadioButton2";
			global::System.Windows.Forms.Control radioButton18 = this.RadioButton2;
			size = new global::System.Drawing.Size(75, 18);
			radioButton18.Size = size;
			this.RadioButton2.TabIndex = 3;
			this.RadioButton2.TabStop = true;
			this.RadioButton2.Text = "Question";
			this.RadioButton2.UseVisualStyleBackColor = true;
			this.PictureBox2.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox2.Image");
			global::System.Windows.Forms.Control pictureBox5 = this.PictureBox2;
			point = new global::System.Drawing.Point(149, 23);
			pictureBox5.Location = point;
			this.PictureBox2.Name = "PictureBox2";
			global::System.Windows.Forms.Control pictureBox6 = this.PictureBox2;
			size = new global::System.Drawing.Size(43, 42);
			pictureBox6.Size = size;
			this.PictureBox2.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
			this.PictureBox2.TabIndex = 2;
			this.PictureBox2.TabStop = false;
			this.RadioButton1.AutoSize = true;
			this.RadioButton1.Checked = true;
			global::System.Windows.Forms.Control radioButton19 = this.RadioButton1;
			point = new global::System.Drawing.Point(16, 78);
			radioButton19.Location = point;
			this.RadioButton1.Name = "RadioButton1";
			global::System.Windows.Forms.Control radioButton20 = this.RadioButton1;
			size = new global::System.Drawing.Size(89, 18);
			radioButton20.Size = size;
			this.RadioButton1.TabIndex = 1;
			this.RadioButton1.TabStop = true;
			this.RadioButton1.Text = "Information";
			this.RadioButton1.UseVisualStyleBackColor = true;
			this.PictureBox1.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox1.Image");
			global::System.Windows.Forms.Control pictureBox7 = this.PictureBox1;
			point = new global::System.Drawing.Point(40, 23);
			pictureBox7.Location = point;
			this.PictureBox1.Name = "PictureBox1";
			global::System.Windows.Forms.Control pictureBox8 = this.PictureBox1;
			size = new global::System.Drawing.Size(43, 42);
			pictureBox8.Size = size;
			this.PictureBox1.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
			this.PictureBox1.TabIndex = 0;
			this.PictureBox1.TabStop = false;
			this.GroupBox21.Controls.Add(this.TextBox5);
			this.GroupBox21.Controls.Add(this.TextBox6);
			this.GroupBox21.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control groupBox27 = this.GroupBox21;
			point = new global::System.Drawing.Point(1, 113);
			groupBox27.Location = point;
			this.GroupBox21.Name = "GroupBox21";
			global::System.Windows.Forms.Control groupBox28 = this.GroupBox21;
			size = new global::System.Drawing.Size(439, 210);
			groupBox28.Size = size;
			this.GroupBox21.TabIndex = 26;
			this.GroupBox21.TabStop = false;
			this.GroupBox21.Text = "MessageBox Content";
			this.TextBox5.BackColor = global::System.Drawing.Color.Black;
			this.TextBox5.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TextBox5.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control textBox3 = this.TextBox5;
			point = new global::System.Drawing.Point(7, 53);
			textBox3.Location = point;
			this.TextBox5.Multiline = true;
			this.TextBox5.Name = "TextBox5";
			global::System.Windows.Forms.Control textBox4 = this.TextBox5;
			size = new global::System.Drawing.Size(424, 150);
			textBox4.Size = size;
			this.TextBox5.TabIndex = 1;
			this.TextBox6.BackColor = global::System.Drawing.Color.Black;
			this.TextBox6.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TextBox6.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control textBox5 = this.TextBox6;
			point = new global::System.Drawing.Point(7, 23);
			textBox5.Location = point;
			this.TextBox6.Name = "TextBox6";
			global::System.Windows.Forms.Control textBox6 = this.TextBox6;
			size = new global::System.Drawing.Size(424, 20);
			textBox6.Size = size;
			this.TextBox6.TabIndex = 0;
			this.Button39.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button39.ForeColor = global::System.Drawing.Color.LimeGreen;
			this.Button39.ImageAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			global::System.Windows.Forms.Control button69 = this.Button39;
			point = new global::System.Drawing.Point(450, 240);
			button69.Location = point;
			this.Button39.Name = "Button39";
			global::System.Windows.Forms.Control button70 = this.Button39;
			size = new global::System.Drawing.Size(177, 39);
			button70.Size = size;
			this.Button39.TabIndex = 24;
			this.Button39.Text = "Send";
			this.Button39.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageBeforeText;
			this.Button39.UseVisualStyleBackColor = true;
			this.Button38.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button38.ForeColor = global::System.Drawing.Color.LimeGreen;
			this.Button38.ImageAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			global::System.Windows.Forms.Control button71 = this.Button38;
			point = new global::System.Drawing.Point(450, 285);
			button71.Location = point;
			this.Button38.Name = "Button38";
			global::System.Windows.Forms.Control button72 = this.Button38;
			size = new global::System.Drawing.Size(177, 39);
			button72.Size = size;
			this.Button38.TabIndex = 23;
			this.Button38.Text = "    Test";
			this.Button38.UseVisualStyleBackColor = true;
			this.Panel1.Controls.Add(this.GroupBox22);
			this.Panel1.Controls.Add(this.GroupBox20);
			this.Panel1.Controls.Add(this.Button38);
			this.Panel1.Controls.Add(this.Button39);
			this.Panel1.Controls.Add(this.GroupBox21);
			this.Panel1.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control panel = this.Panel1;
			point = new global::System.Drawing.Point(109, 12);
			panel.Location = point;
			this.Panel1.Name = "Panel1";
			global::System.Windows.Forms.Control panel2 = this.Panel1;
			size = new global::System.Drawing.Size(638, 327);
			panel2.Size = size;
			this.Panel1.TabIndex = 28;
			this.Panel1.Visible = false;
			this.Panel2.Controls.Add(this.GroupBox16);
			this.Panel2.Controls.Add(this.GroupBox3);
			this.Panel2.Controls.Add(this.GroupBox18);
			this.Panel2.Controls.Add(this.GroupBox9);
			this.Panel2.Controls.Add(this.GroupBox25);
			this.Panel2.Controls.Add(this.GroupBox1);
			this.Panel2.Controls.Add(this.Button56);
			this.Panel2.Controls.Add(this.GroupBox8);
			this.Panel2.Controls.Add(this.GroupBox7);
			this.Panel2.Controls.Add(this.GroupBox2);
			this.Panel2.Controls.Add(this.GroupBox10);
			this.Panel2.Controls.Add(this.GroupBox19);
			this.Panel2.Controls.Add(this.GroupBox6);
			this.Panel2.Controls.Add(this.GroupBox11);
			this.Panel2.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control panel3 = this.Panel2;
			point = new global::System.Drawing.Point(110, 12);
			panel3.Location = point;
			this.Panel2.Name = "Panel2";
			global::System.Windows.Forms.Control panel4 = this.Panel2;
			size = new global::System.Drawing.Size(629, 329);
			panel4.Size = size;
			this.Panel2.TabIndex = 29;
			this.GroupBox16.Controls.Add(this.Button34);
			this.GroupBox16.Controls.Add(this.TextBox1);
			this.GroupBox16.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control groupBox29 = this.GroupBox16;
			point = new global::System.Drawing.Point(351, 73);
			groupBox29.Location = point;
			this.GroupBox16.Name = "GroupBox16";
			global::System.Windows.Forms.Control groupBox30 = this.GroupBox16;
			size = new global::System.Drawing.Size(272, 49);
			groupBox30.Size = size;
			this.GroupBox16.TabIndex = 33;
			this.GroupBox16.TabStop = false;
			this.GroupBox16.Text = "IE Home Page";
			this.Button34.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button34.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control button73 = this.Button34;
			point = new global::System.Drawing.Point(206, 15);
			button73.Location = point;
			this.Button34.Name = "Button34";
			global::System.Windows.Forms.Control button74 = this.Button34;
			size = new global::System.Drawing.Size(61, 25);
			button74.Size = size;
			this.Button34.TabIndex = 13;
			this.Button34.Text = "Change";
			this.Button34.UseVisualStyleBackColor = true;
			this.TextBox1.BackColor = global::System.Drawing.Color.Black;
			this.TextBox1.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TextBox1.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control textBox7 = this.TextBox1;
			point = new global::System.Drawing.Point(9, 20);
			textBox7.Location = point;
			this.TextBox1.Name = "TextBox1";
			global::System.Windows.Forms.Control textBox8 = this.TextBox1;
			size = new global::System.Drawing.Size(191, 20);
			textBox8.Size = size;
			this.TextBox1.TabIndex = 0;
			this.TextBox1.Text = "http://www.Hacker.com/";
			this.GroupBox3.Controls.Add(this.Button5);
			this.GroupBox3.Controls.Add(this.Button6);
			this.GroupBox3.Controls.Add(this.Button7);
			this.GroupBox3.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control groupBox31 = this.GroupBox3;
			point = new global::System.Drawing.Point(1, 0);
			groupBox31.Location = point;
			this.GroupBox3.Name = "GroupBox3";
			global::System.Windows.Forms.Control groupBox32 = this.GroupBox3;
			size = new global::System.Drawing.Size(77, 155);
			groupBox32.Size = size;
			this.GroupBox3.TabIndex = 22;
			this.GroupBox3.TabStop = false;
			this.GroupBox3.Text = "Computer";
			this.Button5.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button5.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button5.Image");
			global::System.Windows.Forms.Control button75 = this.Button5;
			point = new global::System.Drawing.Point(9, 105);
			button75.Location = point;
			this.Button5.Name = "Button5";
			global::System.Windows.Forms.Control button76 = this.Button5;
			size = new global::System.Drawing.Size(58, 40);
			button76.Size = size;
			this.Button5.TabIndex = 8;
			this.Button5.UseVisualStyleBackColor = true;
			this.Button6.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button6.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button6.Image");
			global::System.Windows.Forms.Control button77 = this.Button6;
			point = new global::System.Drawing.Point(9, 18);
			button77.Location = point;
			this.Button6.Name = "Button6";
			global::System.Windows.Forms.Control button78 = this.Button6;
			size = new global::System.Drawing.Size(58, 40);
			button78.Size = size;
			this.Button6.TabIndex = 6;
			this.Button6.UseVisualStyleBackColor = true;
			this.Button7.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button7.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button7.Image");
			global::System.Windows.Forms.Control button79 = this.Button7;
			point = new global::System.Drawing.Point(9, 59);
			button79.Location = point;
			this.Button7.Name = "Button7";
			global::System.Windows.Forms.Control button80 = this.Button7;
			size = new global::System.Drawing.Size(58, 40);
			button80.Size = size;
			this.Button7.TabIndex = 7;
			this.Button7.UseVisualStyleBackColor = true;
			this.Panel4.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.Panel4.Controls.Add(this.Button53);
			global::System.Windows.Forms.Control panel5 = this.Panel4;
			point = new global::System.Drawing.Point(10, 12);
			panel5.Location = point;
			this.Panel4.Name = "Panel4";
			global::System.Windows.Forms.Control panel6 = this.Panel4;
			size = new global::System.Drawing.Size(94, 29);
			panel6.Size = size;
			this.Panel4.TabIndex = 31;
			this.Button53.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.Button53.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button53.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control button81 = this.Button53;
			point = new global::System.Drawing.Point(0, 0);
			button81.Location = point;
			this.Button53.Name = "Button53";
			global::System.Windows.Forms.Control button82 = this.Button53;
			size = new global::System.Drawing.Size(92, 27);
			button82.Size = size;
			this.Button53.TabIndex = 21;
			this.Button53.Text = "MessageBox";
			this.Button53.UseVisualStyleBackColor = true;
			this.Panel6.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.Panel6.Controls.Add(this.Button55);
			global::System.Windows.Forms.Control panel7 = this.Panel6;
			point = new global::System.Drawing.Point(10, 47);
			panel7.Location = point;
			this.Panel6.Name = "Panel6";
			global::System.Windows.Forms.Control panel8 = this.Panel6;
			size = new global::System.Drawing.Size(94, 29);
			panel8.Size = size;
			this.Panel6.TabIndex = 32;
			this.Button55.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.Button55.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Button55.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control button83 = this.Button55;
			point = new global::System.Drawing.Point(0, 0);
			button83.Location = point;
			this.Button55.Name = "Button55";
			global::System.Windows.Forms.Control button84 = this.Button55;
			size = new global::System.Drawing.Size(92, 27);
			button84.Size = size;
			this.Button55.TabIndex = 21;
			this.Button55.Text = "More";
			this.Button55.UseVisualStyleBackColor = true;
			this.Panel7.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.Panel7.Controls.Add(this.Check_Sound);
			this.Panel7.Dock = global::System.Windows.Forms.DockStyle.Left;
			global::System.Windows.Forms.Control panel9 = this.Panel7;
			point = new global::System.Drawing.Point(0, 0);
			panel9.Location = point;
			this.Panel7.Name = "Panel7";
			global::System.Windows.Forms.Control panel10 = this.Panel7;
			size = new global::System.Drawing.Size(100, 346);
			panel10.Size = size;
			this.Panel7.TabIndex = 30;
			global::System.Drawing.SizeF sizeF = new global::System.Drawing.SizeF(7f, 14f);
			this.AutoScaleDimensions = sizeF;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = global::System.Drawing.Color.Black;
			size = new global::System.Drawing.Size(740, 346);
			this.ClientSize = size;
			this.Controls.Add(this.Panel4);
			this.Controls.Add(this.Panel2);
			this.Controls.Add(this.Panel6);
			this.Controls.Add(this.Panel7);
			this.Controls.Add(this.Panel1);
			this.Font = new global::System.Drawing.Font("Arial", 8f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.ForeColor = global::System.Drawing.Color.LimeGreen;
			this.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedSingle;
			this.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
			this.MaximizeBox = false;
			size = new global::System.Drawing.Size(746, 375);
			this.MaximumSize = size;
			size = new global::System.Drawing.Size(746, 375);
			this.MinimumSize = size;
			this.Name = "fun";
			this.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "Fun  ";
			this.GroupBox7.ResumeLayout(false);
			this.GroupBox2.ResumeLayout(false);
			this.GroupBox8.ResumeLayout(false);
			this.GroupBox6.ResumeLayout(false);
			this.GroupBox1.ResumeLayout(false);
			this.GroupBox10.ResumeLayout(false);
			this.GroupBox9.ResumeLayout(false);
			this.GroupBox11.ResumeLayout(false);
			this.GroupBox25.ResumeLayout(false);
			this.GroupBox19.ResumeLayout(false);
			this.GroupBox19.PerformLayout();
			this.GroupBox18.ResumeLayout(false);
			this.GroupBox20.ResumeLayout(false);
			this.GroupBox20.PerformLayout();
			this.GroupBox22.ResumeLayout(false);
			this.GroupBox22.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox4).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox3).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).EndInit();
			this.GroupBox21.ResumeLayout(false);
			this.GroupBox21.PerformLayout();
			this.Panel1.ResumeLayout(false);
			this.Panel2.ResumeLayout(false);
			this.GroupBox16.ResumeLayout(false);
			this.GroupBox16.PerformLayout();
			this.GroupBox3.ResumeLayout(false);
			this.Panel4.ResumeLayout(false);
			this.Panel6.ResumeLayout(false);
			this.Panel7.ResumeLayout(false);
			this.Panel7.PerformLayout();
			this.ResumeLayout(false);
		}

		// Token: 0x040000ED RID: 237
		private global::System.ComponentModel.IContainer components;
	}
}
