namespace NJRAT
{
	// Token: 0x02000026 RID: 38
	
	public partial class STNG : global::System.Windows.Forms.Form
	{
		// Token: 0x06000514 RID: 1300 RVA: 0x00173404 File Offset: 0x00171804
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06000515 RID: 1301 RVA: 0x00173454 File Offset: 0x00171854
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::NJRAT.STNG));
			this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
			this.Snd = new global::System.Windows.Forms.CheckBox();
			this.ShowAlert = new global::System.Windows.Forms.CheckBox();
			this.GroupBox2 = new global::System.Windows.Forms.GroupBox();
			this.LOGLOGIN = new global::System.Windows.Forms.CheckBox();
			this.LOGCONNECTIONS = new global::System.Windows.Forms.CheckBox();
			this.LOGLERR = new global::System.Windows.Forms.CheckBox();
			this.LOGRERR = new global::System.Windows.Forms.CheckBox();
			this.LOGMSGS = new global::System.Windows.Forms.CheckBox();
			this.GroupBox3 = new global::System.Windows.Forms.GroupBox();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.SCI = new global::System.Windows.Forms.ComboBox();
			this.SCAUT = new global::System.Windows.Forms.CheckBox();
			this.GroupBox4 = new global::System.Windows.Forms.GroupBox();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.CAMI = new global::System.Windows.Forms.ComboBox();
			this.CAMAUT = new global::System.Windows.Forms.CheckBox();
			this.GroupBox5 = new global::System.Windows.Forms.GroupBox();
			this.MICI = new global::System.Windows.Forms.ComboBox();
			this.MICAUT = new global::System.Windows.Forms.CheckBox();
			this.GroupBox6 = new global::System.Windows.Forms.GroupBox();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.scrI = new global::System.Windows.Forms.ComboBox();
			this.Button1 = new global::System.Windows.Forms.Button();
			this.GroupBox1.SuspendLayout();
			this.GroupBox2.SuspendLayout();
			this.GroupBox3.SuspendLayout();
			this.GroupBox4.SuspendLayout();
			this.GroupBox5.SuspendLayout();
			this.GroupBox6.SuspendLayout();
			this.SuspendLayout();
			this.GroupBox1.BackColor = global::System.Drawing.Color.Black;
			this.GroupBox1.Controls.Add(this.Snd);
			this.GroupBox1.Controls.Add(this.ShowAlert);
			this.GroupBox1.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control groupBox = this.GroupBox1;
			global::System.Drawing.Point point = new global::System.Drawing.Point(124, 104);
			groupBox.Location = point;
			this.GroupBox1.Name = "GroupBox1";
			this.GroupBox1.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control groupBox2 = this.GroupBox1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(117, 48);
			groupBox2.Size = size;
			this.GroupBox1.TabIndex = 0;
			this.GroupBox1.TabStop = false;
			this.GroupBox1.Text = "OnLogin";
			this.Snd.AutoSize = true;
			this.Snd.BackColor = global::System.Drawing.Color.Black;
			this.Snd.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control snd = this.Snd;
			point = new global::System.Drawing.Point(6, 27);
			snd.Location = point;
			this.Snd.Name = "Snd";
			this.Snd.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control snd2 = this.Snd;
			size = new global::System.Drawing.Size(57, 17);
			snd2.Size = size;
			this.Snd.TabIndex = 1;
			this.Snd.Text = "Sound";
			this.Snd.UseVisualStyleBackColor = false;
			this.ShowAlert.AutoSize = true;
			this.ShowAlert.BackColor = global::System.Drawing.Color.Black;
			this.ShowAlert.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control showAlert = this.ShowAlert;
			point = new global::System.Drawing.Point(6, 11);
			showAlert.Location = point;
			this.ShowAlert.Name = "ShowAlert";
			this.ShowAlert.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control showAlert2 = this.ShowAlert;
			size = new global::System.Drawing.Size(77, 17);
			showAlert2.Size = size;
			this.ShowAlert.TabIndex = 0;
			this.ShowAlert.Text = "Show Alert";
			this.ShowAlert.UseVisualStyleBackColor = false;
			this.GroupBox2.BackColor = global::System.Drawing.Color.Black;
			this.GroupBox2.Controls.Add(this.LOGLOGIN);
			this.GroupBox2.Controls.Add(this.LOGCONNECTIONS);
			this.GroupBox2.Controls.Add(this.LOGLERR);
			this.GroupBox2.Controls.Add(this.LOGRERR);
			this.GroupBox2.Controls.Add(this.LOGMSGS);
			this.GroupBox2.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.GroupBox2.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control groupBox3 = this.GroupBox2;
			point = new global::System.Drawing.Point(124, 1);
			groupBox3.Location = point;
			this.GroupBox2.Name = "GroupBox2";
			this.GroupBox2.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control groupBox4 = this.GroupBox2;
			size = new global::System.Drawing.Size(117, 101);
			groupBox4.Size = size;
			this.GroupBox2.TabIndex = 1;
			this.GroupBox2.TabStop = false;
			this.GroupBox2.Text = "Logs";
			this.LOGLOGIN.AutoSize = true;
			this.LOGLOGIN.BackColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control loglogin = this.LOGLOGIN;
			point = new global::System.Drawing.Point(5, 14);
			loglogin.Location = point;
			this.LOGLOGIN.Name = "LOGLOGIN";
			this.LOGLOGIN.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control loglogin2 = this.LOGLOGIN;
			size = new global::System.Drawing.Size(74, 17);
			loglogin2.Size = size;
			this.LOGLOGIN.TabIndex = 5;
			this.LOGLOGIN.Text = "Login/Out";
			this.LOGLOGIN.UseVisualStyleBackColor = false;
			this.LOGCONNECTIONS.AutoSize = true;
			this.LOGCONNECTIONS.BackColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control logconnections = this.LOGCONNECTIONS;
			point = new global::System.Drawing.Point(5, 30);
			logconnections.Location = point;
			this.LOGCONNECTIONS.Name = "LOGCONNECTIONS";
			this.LOGCONNECTIONS.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control logconnections2 = this.LOGCONNECTIONS;
			size = new global::System.Drawing.Size(85, 17);
			logconnections2.Size = size;
			this.LOGCONNECTIONS.TabIndex = 4;
			this.LOGCONNECTIONS.Text = "Connections";
			this.LOGCONNECTIONS.UseVisualStyleBackColor = false;
			this.LOGLERR.AutoSize = true;
			this.LOGLERR.BackColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control loglerr = this.LOGLERR;
			point = new global::System.Drawing.Point(5, 46);
			loglerr.Location = point;
			this.LOGLERR.Name = "LOGLERR";
			this.LOGLERR.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control loglerr2 = this.LOGLERR;
			size = new global::System.Drawing.Size(87, 17);
			loglerr2.Size = size;
			this.LOGLERR.TabIndex = 3;
			this.LOGLERR.Text = "Listner Errors";
			this.LOGLERR.UseVisualStyleBackColor = false;
			this.LOGRERR.AutoSize = true;
			this.LOGRERR.BackColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control logrerr = this.LOGRERR;
			point = new global::System.Drawing.Point(5, 63);
			logrerr.Location = point;
			this.LOGRERR.Name = "LOGRERR";
			this.LOGRERR.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control logrerr2 = this.LOGRERR;
			size = new global::System.Drawing.Size(93, 17);
			logrerr2.Size = size;
			this.LOGRERR.TabIndex = 2;
			this.LOGRERR.Text = "Remote Errors";
			this.LOGRERR.UseVisualStyleBackColor = false;
			this.LOGMSGS.AutoSize = true;
			this.LOGMSGS.BackColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control logmsgs = this.LOGMSGS;
			point = new global::System.Drawing.Point(5, 80);
			logmsgs.Location = point;
			this.LOGMSGS.Name = "LOGMSGS";
			this.LOGMSGS.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control logmsgs2 = this.LOGMSGS;
			size = new global::System.Drawing.Size(74, 17);
			logmsgs2.Size = size;
			this.LOGMSGS.TabIndex = 1;
			this.LOGMSGS.Text = "Messages";
			this.LOGMSGS.UseVisualStyleBackColor = false;
			this.GroupBox3.BackColor = global::System.Drawing.Color.Black;
			this.GroupBox3.Controls.Add(this.Label1);
			this.GroupBox3.Controls.Add(this.SCI);
			this.GroupBox3.Controls.Add(this.SCAUT);
			this.GroupBox3.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control groupBox5 = this.GroupBox3;
			point = new global::System.Drawing.Point(3, 1);
			groupBox5.Location = point;
			this.GroupBox3.Name = "GroupBox3";
			global::System.Windows.Forms.Control groupBox6 = this.GroupBox3;
			size = new global::System.Drawing.Size(115, 64);
			groupBox6.Size = size;
			this.GroupBox3.TabIndex = 2;
			this.GroupBox3.TabStop = false;
			this.GroupBox3.Text = "Remote Desktop";
			this.Label1.AutoSize = true;
			this.Label1.BackColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control label = this.Label1;
			point = new global::System.Drawing.Point(6, 39);
			label.Location = point;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control label2 = this.Label1;
			size = new global::System.Drawing.Size(27, 13);
			label2.Size = size;
			this.Label1.TabIndex = 3;
			this.Label1.Text = "Size";
			this.SCI.BackColor = global::System.Drawing.Color.Black;
			this.SCI.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.SCI.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.SCI.ForeColor = global::System.Drawing.Color.LimeGreen;
			this.SCI.FormattingEnabled = true;
			this.SCI.Items.AddRange(new object[]
			{
				"%100", "%95", "%90", "%85", "%80", "%75", "%70", "%65", "%60", "%55",
				"%50"
			});
			global::System.Windows.Forms.Control sci = this.SCI;
			point = new global::System.Drawing.Point(38, 36);
			sci.Location = point;
			this.SCI.Name = "SCI";
			global::System.Windows.Forms.Control sci2 = this.SCI;
			size = new global::System.Drawing.Size(71, 21);
			sci2.Size = size;
			this.SCI.TabIndex = 2;
			this.SCAUT.AutoSize = true;
			this.SCAUT.BackColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control scaut = this.SCAUT;
			point = new global::System.Drawing.Point(6, 19);
			scaut.Location = point;
			this.SCAUT.Name = "SCAUT";
			this.SCAUT.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control scaut2 = this.SCAUT;
			size = new global::System.Drawing.Size(70, 17);
			scaut2.Size = size;
			this.SCAUT.TabIndex = 1;
			this.SCAUT.Text = "AutoStart";
			this.SCAUT.UseVisualStyleBackColor = false;
			this.GroupBox4.BackColor = global::System.Drawing.Color.Black;
			this.GroupBox4.Controls.Add(this.Label2);
			this.GroupBox4.Controls.Add(this.CAMI);
			this.GroupBox4.Controls.Add(this.CAMAUT);
			this.GroupBox4.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control groupBox7 = this.GroupBox4;
			point = new global::System.Drawing.Point(3, 68);
			groupBox7.Location = point;
			this.GroupBox4.Name = "GroupBox4";
			global::System.Windows.Forms.Control groupBox8 = this.GroupBox4;
			size = new global::System.Drawing.Size(115, 64);
			groupBox8.Size = size;
			this.GroupBox4.TabIndex = 3;
			this.GroupBox4.TabStop = false;
			this.GroupBox4.Text = "Remote Cam";
			this.Label2.AutoSize = true;
			this.Label2.BackColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control label3 = this.Label2;
			point = new global::System.Drawing.Point(6, 39);
			label3.Location = point;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control label4 = this.Label2;
			size = new global::System.Drawing.Size(27, 13);
			label4.Size = size;
			this.Label2.TabIndex = 3;
			this.Label2.Text = "Size";
			this.CAMI.BackColor = global::System.Drawing.Color.Black;
			this.CAMI.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.CAMI.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.CAMI.ForeColor = global::System.Drawing.Color.LimeGreen;
			this.CAMI.FormattingEnabled = true;
			this.CAMI.Items.AddRange(new object[]
			{
				"%100", "%95", "%90", "%85", "%80", "%75", "%70", "%65", "%60", "%55",
				"%50"
			});
			global::System.Windows.Forms.Control cami = this.CAMI;
			point = new global::System.Drawing.Point(38, 36);
			cami.Location = point;
			this.CAMI.Name = "CAMI";
			global::System.Windows.Forms.Control cami2 = this.CAMI;
			size = new global::System.Drawing.Size(71, 21);
			cami2.Size = size;
			this.CAMI.TabIndex = 2;
			this.CAMAUT.AutoSize = true;
			this.CAMAUT.BackColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control camaut = this.CAMAUT;
			point = new global::System.Drawing.Point(6, 19);
			camaut.Location = point;
			this.CAMAUT.Name = "CAMAUT";
			this.CAMAUT.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control camaut2 = this.CAMAUT;
			size = new global::System.Drawing.Size(70, 17);
			camaut2.Size = size;
			this.CAMAUT.TabIndex = 1;
			this.CAMAUT.Text = "AutoStart";
			this.CAMAUT.UseVisualStyleBackColor = false;
			this.GroupBox5.BackColor = global::System.Drawing.Color.Black;
			this.GroupBox5.Controls.Add(this.MICI);
			this.GroupBox5.Controls.Add(this.MICAUT);
			this.GroupBox5.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control groupBox9 = this.GroupBox5;
			point = new global::System.Drawing.Point(3, 138);
			groupBox9.Location = point;
			this.GroupBox5.Name = "GroupBox5";
			global::System.Windows.Forms.Control groupBox10 = this.GroupBox5;
			size = new global::System.Drawing.Size(115, 75);
			groupBox10.Size = size;
			this.GroupBox5.TabIndex = 4;
			this.GroupBox5.TabStop = false;
			this.GroupBox5.Text = "Remote MIC";
			this.MICI.BackColor = global::System.Drawing.Color.Black;
			this.MICI.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.MICI.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.MICI.ForeColor = global::System.Drawing.Color.LimeGreen;
			this.MICI.FormattingEnabled = true;
			this.MICI.Items.AddRange(new object[] { "4 kb 8bit", "6 kb 8bit", "8 kb 8bit", "8 kb 16bit", "12 kb 16bit", "16 kb 16bit", "20 kb 16bit", "24 kb 16bit" });
			global::System.Windows.Forms.Control mici = this.MICI;
			point = new global::System.Drawing.Point(6, 36);
			mici.Location = point;
			this.MICI.Name = "MICI";
			global::System.Windows.Forms.Control mici2 = this.MICI;
			size = new global::System.Drawing.Size(103, 21);
			mici2.Size = size;
			this.MICI.TabIndex = 2;
			this.MICAUT.AutoSize = true;
			this.MICAUT.BackColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control micaut = this.MICAUT;
			point = new global::System.Drawing.Point(6, 19);
			micaut.Location = point;
			this.MICAUT.Name = "MICAUT";
			this.MICAUT.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control micaut2 = this.MICAUT;
			size = new global::System.Drawing.Size(70, 17);
			micaut2.Size = size;
			this.MICAUT.TabIndex = 1;
			this.MICAUT.Text = "AutoStart";
			this.MICAUT.UseVisualStyleBackColor = false;
			this.GroupBox6.BackColor = global::System.Drawing.Color.Black;
			this.GroupBox6.Controls.Add(this.Label3);
			this.GroupBox6.Controls.Add(this.scrI);
			this.GroupBox6.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control groupBox11 = this.GroupBox6;
			point = new global::System.Drawing.Point(124, 154);
			groupBox11.Location = point;
			this.GroupBox6.Name = "GroupBox6";
			this.GroupBox6.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control groupBox12 = this.GroupBox6;
			size = new global::System.Drawing.Size(117, 59);
			groupBox12.Size = size;
			this.GroupBox6.TabIndex = 5;
			this.GroupBox6.TabStop = false;
			this.GroupBox6.Text = "Screen";
			this.Label3.AutoSize = true;
			this.Label3.BackColor = global::System.Drawing.Color.Black;
			this.Label3.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label5 = this.Label3;
			point = new global::System.Drawing.Point(5, 14);
			label5.Location = point;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control label6 = this.Label3;
			size = new global::System.Drawing.Size(89, 14);
			label6.Size = size;
			this.Label3.TabIndex = 3;
			this.Label3.Text = "Refresh Speed";
			this.scrI.BackColor = global::System.Drawing.Color.Black;
			this.scrI.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.scrI.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.scrI.ForeColor = global::System.Drawing.Color.LimeGreen;
			this.scrI.FormattingEnabled = true;
			this.scrI.Items.AddRange(new object[] { "Ultra", "Fast", "Good", "Slow", "Slower" });
			global::System.Windows.Forms.Control scrI = this.scrI;
			point = new global::System.Drawing.Point(6, 31);
			scrI.Location = point;
			this.scrI.Name = "scrI";
			this.scrI.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control scrI2 = this.scrI;
			size = new global::System.Drawing.Size(105, 21);
			scrI2.Size = size;
			this.scrI.TabIndex = 2;
			this.Button1.BackColor = global::System.Drawing.Color.Black;
			this.Button1.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button1.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Button1.ForeColor = global::System.Drawing.Color.LimeGreen;
			global::System.Windows.Forms.Control button = this.Button1;
			point = new global::System.Drawing.Point(3, 219);
			button.Location = point;
			this.Button1.Name = "Button1";
			global::System.Windows.Forms.Control button2 = this.Button1;
			size = new global::System.Drawing.Size(238, 25);
			button2.Size = size;
			this.Button1.TabIndex = 6;
			this.Button1.Text = "Save";
			this.Button1.UseVisualStyleBackColor = false;
			global::System.Drawing.SizeF sizeF = new global::System.Drawing.SizeF(6f, 13f);
			this.AutoScaleDimensions = sizeF;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = global::System.Drawing.SystemColors.ActiveCaptionText;
			size = new global::System.Drawing.Size(244, 248);
			this.ClientSize = size;
			this.Controls.Add(this.Button1);
			this.Controls.Add(this.GroupBox6);
			this.Controls.Add(this.GroupBox5);
			this.Controls.Add(this.GroupBox4);
			this.Controls.Add(this.GroupBox3);
			this.Controls.Add(this.GroupBox2);
			this.Controls.Add(this.GroupBox1);
			this.ForeColor = global::System.Drawing.Color.Black;
			this.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedSingle;
			this.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
			this.MaximizeBox = false;
			this.Name = "STNG";
			this.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "Settings";
			this.GroupBox1.ResumeLayout(false);
			this.GroupBox1.PerformLayout();
			this.GroupBox2.ResumeLayout(false);
			this.GroupBox2.PerformLayout();
			this.GroupBox3.ResumeLayout(false);
			this.GroupBox3.PerformLayout();
			this.GroupBox4.ResumeLayout(false);
			this.GroupBox4.PerformLayout();
			this.GroupBox5.ResumeLayout(false);
			this.GroupBox5.PerformLayout();
			this.GroupBox6.ResumeLayout(false);
			this.GroupBox6.PerformLayout();
			this.ResumeLayout(false);
		}

		// Token: 0x04000260 RID: 608
		private global::System.ComponentModel.IContainer components;
	}
}
